latent_size: 100
negative_slope: 0.2

generator_conv1: [100, 512, 4, 1, 0]
generator_conv2: [512, 256, 4, 2, 1]
generator_conv3: [256, 128, 4, 2, 1]
generator_conv4: [128, 64, 4, 2, 1]
generator_conv5: [64, 3, 4, 2, 1]

discriminator_conv1: [3, 64, 4, 2, 1]
discriminator_conv2: [64, 128, 4, 2, 1]
discriminator_conv3: [128, 256, 4, 2, 1]
discriminator_conv4: [256, 512, 4, 2, 1]
discriminator_conv5: [512, 1, 4, 1, 0]